project:
  type: book
  output-dir: docs 

book:
  title: "PySimp"
  author: "Zafer Kosar"
  date: "06/09/2024"
  chapters:
    - index.qmd
    - part: Installation
      chapters:
        - 00_Installation/00_Python.ipynb
        - 00_Installation/01_Libraries.ipynb
    - part: Basics
      chapters:
        - 01_Basics/00_Variables.ipynb
        - 01_Basics/01_Lists.ipynb
        - 01_Basics/02_Tuples.ipynb
        - 01_Basics/03_Dictionaries.ipynb
    - part: Conditionals
      chapters:
        - 02_Conditionals/00_Operators.ipynb
        - 02_Conditionals/01_IfConditionals.ipynb
    - part: Loops
      chapters:
        - 03_Loops/00_ForLoops.ipynb
        - 03_Loops/01_WhileLoops.ipynb


format:
  html:
    theme: 
      light: Cosmo
      dark: Vapor
    highlight-style: github
    monofont: "Cascadia Mono SemiBold"
    code-block-bg: "#efefef"